development:
    adapter: mysql2
    encoding: utf8
    database: mcp_dev
    pool: 5
    username: root
    password:
    timeout: 5000

test:
    adapter: mysql2
    encoding: utf8
    database: mcp_test
    pool: 5
    username: root
    password:
    timeout: 5000

production:
    adapter: mysql2
    encoding: utf8
    database: mcp_prod
    username: root
    password:
    pool: 5
    timeout: 5000
